# Generated by Django 3.2.3 on 2024-11-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20241112_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_of_measure',
            new_name='measurement_unit',
        ),
    ]
