# Generated by Django 3.2.3 on 2024-11-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientsinrecipe',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ingredientsinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
