# Generated by Django 3.2.3 on 2024-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241114_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
