# Generated by Django 3.2.3 on 2024-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/media/userpic-icon.jpg', null=True, upload_to='users/avatars/'),
        ),
    ]
