# Generated by Django 3.2.3 on 2024-11-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default_avatar.jpg', null=True, upload_to='users/avatars/'),
        ),
    ]
